--- #YAML:1.0
name:               Perl6-Perldoc
version:            0.000008
abstract:           Use Perl 6 documentation in a Perl 5 program
author:
    - Damian Conway <DCONWAY@CPAN.org>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Filter::Simple:  0
    Scalar::Util:    0
    Test::More:      0
    version:         0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.57_05
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
